export const START_TYPING_MESSAGE = 'START_TYPING_MESSAGE';
export const END_TYPING_MESSAGE = 'END_TYPING_MESSAGE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const NOT_ERROR_MESSAGE = 'NOT_ERROR_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
